### ISSUE TITLE
add metrics support

### ISSUE THREAD

**Issue by jgilbert01** [jgilbert01/aws-lambda-stream#21]
* size of batch
* pipeline start and end timer
* eventType ratio
* other
* cw, datadog, other
* toPromise2 that returns metrics
* dynamodb capacity units?
* enable/disable via global/local options ?

**Comment by petermyers** [comment]
In addition to what you listed above:
- Lambda Xray integration
- New relic?
- Memory cache hits / misses
- Timing data - beyond just start and end timers for the pipeline, I'm thinking about enabling performance profiling. A utility you wrap pipeline steps in that adds additional timing data at a more granular level
- Pipeline ratios for batch - More so than just eventTypes since in practice a single event type might get processed by multiple pipelines

**Comment by jgilbert01** [comment]
- defines a standard "metrics" field on uow
- sinks/queries/steps/etc will add metrics as appropriate to the uow
- a new toPromiseWithMetrics which will create histograms from uow.metrics per pipeline with min/avg/max/etc
- and write the metrics as cloudwatch logs embedded metrics
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html
- return subset of metrics instead of Success

**Comment by petermyers** [comment]
Can we call this issue resolved at this point?
