### ISSUE TITLE
Best practices on reacting to data change in same service?

### ISSUE THREAD

**Issue by vsnig** [jgilbert01/aws-lambda-stream#91]
Hi John,

Could you please clarify this thing to me.

I have a situation where I need to do some job reacting to entity data change in the same service.

I see 2 main options:

1)
* Entity data is changed
* Trigger emits CDC event
* Listener listens to own CDC event and does the job.

2)
* Entity data is changed
* Trigger emits CDC event
* Another trigger pipeline does the job on changed data.

The first one uses familiar patterns and feels less 'custom'. But there's some doubt about publishing/listening to own events all across event hub.

The second does everything locally but brings some complexity because multiple trigger pipelines react to same event making tests a little less straight forward.

Both seems viable to me but I like first a little bit more. 

Can you please drop couple of words which one you think is best and why.

Thanks!

**Comment by jgilbert01** [comment]
Great question. Both approaches are valid.
The materialize pipeline currently filters out based on the source tag as part of the latching mechanism. but that could/should be rule driven.
I'll use the trigger side when i don't want to create an event just yet.
we can probably come up with ways to make testing easier, so that testing is not a limiting factor.
the control service pattern i use for orchestration and snapshots definitely consumes its own events. so there shouldn't be any doubt about that approach.
any and all events that pass thru the hub become valuable metrics downstream.
when everything else is equal, go with your gut!!

**Comment by vsnig** [comment]
Yep, the CDC event is emitted regardless of this job. "Listener" variant looks cleaner. 
Thanks for the reply!
